In [8]:
import pandas as pd
#encoding='latin1', encoding='ISO-8859-1', encoding='utf-8' ou então encoding='cp1252'

vendas = pd.read_csv(r'dados/Contoso - Vendas  - 2017.csv', sep=';')
produtos = pd.read_csv(r'dados/Contoso - Cadastro Produtos.csv', sep=';')
lojas = pd.read_csv(r'dados/Contoso - Lojas.csv', sep=';')
clientes = pd.read_csv(r'dados/Contoso - Clientes.csv', sep=';')
#Excluindo Colunas
clientes = clientes[['ID Cliente', 'E-mail']]
produtos = produtos[['ID Produto', 'Categoria']]
lojas = lojas[['ID Loja', 'Nome da Loja']]

vendas = vendas.merge(produtos, on='ID Produto')
vendas = vendas.merge(lojas, on='ID Loja')
vendas = vendas.merge(clientes, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})

display(vendas)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,Câmera Digital,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Home Theater,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
2,191019,20/03/2017,21/03/2017,1,172,376,2,6825,9,0,Laptop,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp
3,18610,08/01/2017,10/01/2017,2,200,448,2,6825,48,0,Desktop,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp
4,287704,23/04/2017,26/04/2017,3,76,280,1,6825,10,0,Home Theater,Loja Contoso Beaumont No.1,rbrumfieldmy@ameblo.jp
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,878244,23/11/2017,23/11/2017,0,110,889,4,347,12,1,Acessório para Computador,Loja Contoso Orlando,edowner9m@imdb.com
980638,920243,09/12/2017,10/12/2017,1,261,1367,5,38781,13,0,Telefone para Casa & Escritório,Loja Contoso Damascus No.1,ruben31@adventure-works.com
980639,467482,21/06/2017,25/06/2017,4,115,269,1,553,10,0,Home Theater,Loja Contoso New York No.1,akuhnertfc@themeforest.net
980640,853643,13/11/2017,20/11/2017,7,115,809,4,38860,6,0,Acessório para Computador,Loja Contoso New York No.1,anne5@adventure-works.com
980641,903958,02/12/2017,02/12/2017,0,222,1435,10,815,8,0,Smartphone,Loja Contoso Roma,ekorneevmm@instagram.com

# % De das vendas devolvidas

In [15]:
quant_vendas = vendas['Quantidade Vendida'].sum()
quant_devolvidas = vendas['Quantidade Devolvida'].sum()

print("{:.2%}".format(quant_devolvidas / quant_vendas))

1.17%

# Para saber a % de devoluções de uma loja específica ex. Loja C Europe Online

In [27]:
vendas_europeonline = vendas[vendas['ID Loja'] == 306]
qt_devolvida = vendas_europeonline['Quantidade Devolvida'].sum()
qt_vendida = vendas_europeonline['Quantidade Vendida'].sum()
print("{:.2%}".format(qt_devolvida / qt_vendida))

1.33%

# Entendendo o que está acontecendo

In [31]:
loja306 = vendas['ID Loja'] == 306
print(loja306)

0         False
1          True
2         False
3         False
4         False
          ...
980637    False
980638    False
980639    False
980640    False
980641    False
Name: ID Loja, Length: 980642, dtype: bool

# Loja 306 sem devoluções

In [37]:
loja306ZeroVendas = vendas[(vendas['ID Loja'] == 306) & (vendas['Quantidade Devolvida'] == 0)]
display(loja306ZeroVendas)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail do Cliente
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Home Theater,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
17,614980,18/08/2017,18/08/2017,0,306,1621,9,21344,4,0,Filme DVD,Loja Contoso Europe Online,makayla3@adventure-works.com
18,786402,21/10/2017,25/10/2017,4,306,226,10,21344,8,0,Home Theater,Loja Contoso Europe Online,makayla3@adventure-works.com
19,383897,25/05/2017,28/05/2017,3,306,347,1,21344,20,0,Laptop,Loja Contoso Europe Online,makayla3@adventure-works.com
77,559478,26/07/2017,29/07/2017,3,306,1382,1,24440,5,0,Telefone para Casa & Escritório,Loja Contoso Europe Online,noah55@adventure-works.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885329,865745,18/11/2017,24/11/2017,6,306,823,10,9259,8,0,Acessório para Computador,Loja Contoso Europe Online,mplaskitt78@marriott.com
885356,907944,04/12/2017,04/12/2017,0,306,208,10,18529,8,0,Home Theater,Loja Contoso Europe Online,eribchesteres@pbs.org
885386,919123,08/12/2017,08/12/2017,0,306,208,10,38811,8,0,Home Theater,Loja Contoso Europe Online,jessica47@adventure-works.com
885390,964452,25/12/2017,25/12/2017,0,306,192,10,30633,8,0,Home Theater,Loja Contoso Europe Online,terrence23@adventure-works.com
885415,900861,01/12/2017,05/12/2017,4,306,224,10,8596,8,0,Home Theater,Loja Contoso Europe Online,cmordangl@webnode.com