# Adicionando Colunas, Modificando Colunas e Valores

In [1]:
import pandas as pd
#encoding='latin1', encoding='ISO-8859-1', encoding='utf-8' ou então encoding='cp1252'

vendas = pd.read_csv(r'dados/Contoso - Vendas  - 2017.csv', sep=';')
produtos = pd.read_csv(r'dados/Contoso - Cadastro Produtos.csv', sep=';')
lojas = pd.read_csv(r'dados/Contoso - Lojas.csv', sep=';')
clientes = pd.read_csv(r'dados/Contoso - Clientes.csv', sep=';')
#Excluindo Colunas
clientes = clientes[['ID Cliente', 'E-mail']]
produtos = produtos[['ID Produto', 'Categoria']]
lojas = lojas[['ID Loja', 'Nome da Loja']]

vendas = vendas.merge(produtos, on='ID Produto')
vendas = vendas.merge(lojas, on='ID Loja')
vendas = vendas.merge(clientes, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})

display(vendas)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,Câmera Digital,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,880458,23/11/2017,23/11/2017,0,306,235,10,6825,8,0,Home Theater,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp
2,191019,20/03/2017,21/03/2017,1,172,376,2,6825,9,0,Laptop,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp
3,18610,08/01/2017,10/01/2017,2,200,448,2,6825,48,0,Desktop,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp
4,287704,23/04/2017,26/04/2017,3,76,280,1,6825,10,0,Home Theater,Loja Contoso Beaumont No.1,rbrumfieldmy@ameblo.jp
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,878244,23/11/2017,23/11/2017,0,110,889,4,347,12,1,Acessório para Computador,Loja Contoso Orlando,edowner9m@imdb.com
980638,920243,09/12/2017,10/12/2017,1,261,1367,5,38781,13,0,Telefone para Casa & Escritório,Loja Contoso Damascus No.1,ruben31@adventure-works.com
980639,467482,21/06/2017,25/06/2017,4,115,269,1,553,10,0,Home Theater,Loja Contoso New York No.1,akuhnertfc@themeforest.net
980640,853643,13/11/2017,20/11/2017,7,115,809,4,38860,6,0,Acessório para Computador,Loja Contoso New York No.1,anne5@adventure-works.com
980641,903958,02/12/2017,02/12/2017,0,222,1435,10,815,8,0,Smartphone,Loja Contoso Roma,ekorneevmm@instagram.com

## Acrescentando um COLUNA com mês, dia e ano de cada venda
Não só a data completa

In [3]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 980642 entries, 0 to 980641
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  object
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Categoria             980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
dtypes: int64(8), object(5)
memory usage: 104.7+ MB

In [12]:
vendas['Data da Venda'] = pd.to_datetime(vendas['Data da Venda'], format="%d/%m/%Y")
vendas['Ano da Venda'] = vendas['Data da Venda'].dt.year
vendas['Mês da Venda'] = vendas['Data da Venda'].dt.month
vendas['Dia da Venda'] = vendas['Data da Venda'].dt.day


#É possível notar que o TYPE de Data da Venda agora é "datetime[ns]"
vendas.info()
display(vendas)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 980642 entries, 0 to 980641
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  datetime64[ns]
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Categoria             980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
 13  Ano da Venda          980642 non-null  int64
 14  Mês da Venda          980642 non-null  int64
 15  Dia da Venda          980642 non-null  int64
dtypes: datetime64[ns](1), int64(11), object(4)
memory usage: 127.2+ MB

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail do Cliente,Ano da Venda,Mês da Venda,Dia da Venda
0,1,2017-01-01,02/01/2017,1,86,981,2,6825,9,1,Câmera Digital,Loja Contoso Austin,rbrumfieldmy@ameblo.jp,2017,1,1
1,880458,2017-11-23,23/11/2017,0,306,235,10,6825,8,0,Home Theater,Loja Contoso Europe Online,rbrumfieldmy@ameblo.jp,2017,11,23
2,191019,2017-03-20,21/03/2017,1,172,376,2,6825,9,0,Laptop,Loja Contoso Hartford,rbrumfieldmy@ameblo.jp,2017,3,20
3,18610,2017-01-08,10/01/2017,2,200,448,2,6825,48,0,Desktop,Loja Contoso Catalog,rbrumfieldmy@ameblo.jp,2017,1,8
4,287704,2017-04-23,26/04/2017,3,76,280,1,6825,10,0,Home Theater,Loja Contoso Beaumont No.1,rbrumfieldmy@ameblo.jp,2017,4,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,878244,2017-11-23,23/11/2017,0,110,889,4,347,12,1,Acessório para Computador,Loja Contoso Orlando,edowner9m@imdb.com,2017,11,23
980638,920243,2017-12-09,10/12/2017,1,261,1367,5,38781,13,0,Telefone para Casa & Escritório,Loja Contoso Damascus No.1,ruben31@adventure-works.com,2017,12,9
980639,467482,2017-06-21,25/06/2017,4,115,269,1,553,10,0,Home Theater,Loja Contoso New York No.1,akuhnertfc@themeforest.net,2017,6,21
980640,853643,2017-11-13,20/11/2017,7,115,809,4,38860,6,0,Acessório para Computador,Loja Contoso New York No.1,anne5@adventure-works.com,2017,11,13
980641,903958,2017-12-02,02/12/2017,0,222,1435,10,815,8,0,Smartphone,Loja Contoso Roma,ekorneevmm@instagram.com,2017,12,2

#